ritesh:
	@g++ -std=c++11 -o ritesh cpp-implementation/main.cpp cpp-implementation/mergeSort.cpp cpp-implementation/parallelMergeSort.cpp -pthread

shreyas:
	@gcc -o shreyas c-implementation/{main.c,mergeSort.c,parallelMergeSort.c}
